apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi-deployment
  labels:
    app: nifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: nifi
        image: vikal190/nifi-latest:latest
        ports:
        - containerPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: nifi-service
spec:
  selector:
    app: nifi
  ports:
    - protocol: TCP
      port: 9093
      targetPort: 9093
  type: NodePort
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nifi-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var"
